steps:
  - name: node:18-alpine
    entrypoint: npm
    args: ["install"]

  - name: node:18-alpine
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "REACT_APP_FIREBASE_API_KEY"=${_FIREBASE_API_KEY}"
      - "REACT_APP_FIREBASE_APP_ID"=${_FIREBASE_APP_ID}
      - "REACT_APP_FIREBASE_AUTH_DOMAIN"=${_FIREBASE_AUTH_DOMAIN}
      - "REACT_APP_FIREBASE_STORAGE_BUCKET"=${_FIREBASE_STORAGE_BUCKET}
      - "REACT_APP_FIREBASE_MESSAGING_SENDER_ID"=${_FIREBASE_MESSAGING_SENDER_ID}
      - "REACT_APP_PROJECT_ID"=${_PROJECT}

  - name: node:18-alpine
    entrypoint: npm
    args: ["run", "build"]

  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT}/github.com/${_ACCOUNT}/${_IMAGE}:$SHORT_SHA', '.' ]

  - id: 'push image to artifactory'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${_PROJECT}/github.com/${_ACCOUNT}/${_IMAGE}:$SHORT_SHA' ]

  - id: 'cloud run deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', '${_APP}',
            '--region=${_REGION}',
            '--port=443',
            '--allow-unauthenticated',
            '--platform=managed',
            '--image=gcr.io/${_PROJECT}/github.com/${_ACCOUNT}/${_IMAGE}:$SHORT_SHA' ]
